
version: '3'

services:
  app:
    container_name: chopinhauer-springboot-postgresql
    image: app-springboot-postgresql
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chopinhauer_db
