
version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      #- POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chopinhauer_db
    volumes:
      - ./var/lib/postgresql/data
